// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzoGa7XVDUl50dosL6Pwy2fpuTaDUEtZs',
    appId: '1:544672755260:web:15f845cd53778d5490dd39',
    messagingSenderId: '544672755260',
    projectId: 'riversense-lite',
    authDomain: 'riversense-lite.firebaseapp.com',
    storageBucket: 'riversense-lite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfIZncmELrZrms4zhs1PN-RZW8EZ27gvg',
    appId: '1:544672755260:android:9a6dd4b531352ae890dd39',
    messagingSenderId: '544672755260',
    projectId: 'riversense-lite',
    storageBucket: 'riversense-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFY0L-ojKh11WZ7vl0eVY9oRhIMD7GOtk',
    appId: '1:544672755260:ios:9416bc8ff3439f7b90dd39',
    messagingSenderId: '544672755260',
    projectId: 'riversense-lite',
    storageBucket: 'riversense-lite.firebasestorage.app',
    iosBundleId: 'com.example.riversenseLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFY0L-ojKh11WZ7vl0eVY9oRhIMD7GOtk',
    appId: '1:544672755260:ios:9416bc8ff3439f7b90dd39',
    messagingSenderId: '544672755260',
    projectId: 'riversense-lite',
    storageBucket: 'riversense-lite.firebasestorage.app',
    iosBundleId: 'com.example.riversenseLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzoGa7XVDUl50dosL6Pwy2fpuTaDUEtZs',
    appId: '1:544672755260:web:da667ad8e5a659f390dd39',
    messagingSenderId: '544672755260',
    projectId: 'riversense-lite',
    authDomain: 'riversense-lite.firebaseapp.com',
    storageBucket: 'riversense-lite.firebasestorage.app',
  );
}
